name: dynamic_themes
description: Allows you to specify a number of color themes for the user to choose from. Persits the selected theme across app restarts.
version: 0.1.0+1
repository: https://github.com/JulianAssmann/flutter_dynamic_themes

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: